name: TestSiteWhatever
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8209
title: This is your site title
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff00b8'
    - '#00ff90'
    - '#004527'
    - '#00ac65'
  brandStrength: 0.4375
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0.9575153316836804
purpose: []
